In [1]:
import numpy as np
import torch

d:\soft\Anaconda3\envs\py37\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [10]:
np0 = np.zeros((10,10))

In [15]:
ts0 = torch.zeros(10).cuda()

In [17]:
print(np0.size)
print(ts0.size())

100
torch.Size([10])


In [18]:
print(np0.shape)
print(ts0.shape)


(10, 10)
torch.Size([10])


In [13]:
np.info(np.zeros)

zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------
zeros_lik

In [24]:
np0 = np.arange(0,10)
ts0 = torch.arange(0,10)
print(np0)
print(ts0)

[0 1 2 3 4 5 6 7 8 9]
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [37]:
print(np0[::-1])

#然后使用torch.flip翻转
z=torch.flip(ts0,[0])
print(z)

[9 8 7 6 5 4 3 2 1 0]
tensor([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])


In [39]:
torch.arange(0,9).reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [40]:
torch.nonzero(torch.tensor([2,4,0,6,0]))

tensor([[0],
        [1],
        [3]])

In [42]:
ts0[[2,8]]

tensor([2, 8])

In [46]:
ts0[[False,True,False,True,False,True,False,True,False,True]]

tensor([1, 3, 5, 7, 9])