### 列表转数组

In [2]:
import numpy as np
list1=[[1,2,3],[4,5,6],[7,8,9]]
np1=np.array(list1)
print(list1)
print(np1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### numpy的索引

索引也可以是一个数组

In [2]:
np1 = [0,1,2,1,3,4,3]
np2 = [17,16,18,19,1,6,8]
depth_map =  np.array([[1,],[2,],[3,],[4,],[5,]])
print(depth_map)
depth_map[np1,0]  = np2
print(depth_map)


[[1]
 [2]
 [3]
 [4]
 [5]]
[[17]
 [19]
 [18]
 [ 8]
 [ 6]]


Mask

In [7]:
x =  np.array([[1,2,3],[1,2,3],[1,2,3]])
print(x)
print(x[[1,2,1,1,1],[0,1,1,1,1]])
mask = np.array([[False,True,True],[False,True,True],[False,True,True]])
print(x[mask])

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[1 2 2 2 2]
[2 3 2 3 2 3]


In [11]:
x =  np.array([[1,2],[3,4]])
y = np.array([[False,True,],[True,False]])
print(x[:][y])
print(x)

[2 3]
[[1 2]
 [3 4]]


### 索引第一个矩阵是x，第二个矩阵是y

In [17]:
print(x[[0,1,0],[1,1,1]])

[2 4 2]


In [9]:
np1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np1[:2]#从头到2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np1[::2]#步进是2

array([[1, 2, 3],
       [7, 8, 9]])

In [12]:
np1[:,2]#第二列！！！！

array([3, 6, 9])

In [8]:
np1=np.array([[1,2,2],[4,5,6],[7,8,9]])
np1.clip(0,1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

最大值索引

In [9]:
np.argmax(np1)

8

In [11]:
np1.size

9

In [12]:
np1.shape

(3, 3)

### reshape

In [10]:
import numpy as np
np_data=np.arange(6).reshape((2,3))

print(np_data.size)
print(np_data.shape)

6
(2, 3)


### 压缩zip

In [2]:
x1=zip(np1)
for i in x1:
    print(i)

(array([1, 2, 3]),)
(array([4, 5, 6]),)
(array([7, 8, 9]),)


In [3]:
x2=zip(*np1)
for i in x2:
    print(i)

(1, 4, 7)
(2, 5, 8)
(3, 6, 9)


### dot计算数量积

In [5]:
import numpy as np
x=np.random.randn(1,3)
y=np.random.randn(3,1)
print(x)
print(y)
print(x.dot(y))

[[-0.27472411 -1.15735478 -0.92547488]]
[[-0.40426297]
 [ 0.32872896]
 [ 0.26240489]]
[[-0.51224439]]


In [4]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c= np.dot(a,b)#计算出数量积
print(c)
toc = time.time()
print("vecterized "+str(1000*(toc-tic))+'ms')

250152.08531622158
vecterized 9.956598281860352ms


### 指数 绝对值  最大值  对数 倒数 平方

In [53]:
v = np.random.randn(5)
print(v)
v = np.random.rand(5)
print(v)
print(np.exp(v))#指数
print(np.abs(v))#绝对值
print(np.maximum(v,0))#最大值
print(np.log(v))#对数
print(1/v)#倒数
print(v**2)#平方

[ 2.22354498 -0.40169898  0.21218203 -0.84025399 -0.15381942]
[0.32714191 0.62926441 0.41486842 0.279161   0.3305412 ]
[1.3869983  1.87622993 1.5141715  1.32202017 1.39172112]
[0.32714191 0.62926441 0.41486842 0.279161   0.3305412 ]
[0.32714191 0.62926441 0.41486842 0.279161   0.3305412 ]
[-1.11736122 -0.46320375 -0.87979386 -1.27596662 -1.10702398]
[3.05677739 1.5891571  2.41040278 3.58216232 3.0253415 ]
[0.10702183 0.39597369 0.17211581 0.07793086 0.10925748]


In [28]:
A=np.array([[56 , 0 ,4.4,68],
            [1.2,104, 52,8 ],
            [1.8,135, 99,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


###  按维度求和和reshape

In [37]:
cal=A.sum(axis=0)
print(cal)
type(cal)
print(cal.reshape(1,4))

[ 59.  239.  155.4  76.9]
[[ 59.  239.  155.4  76.9]]


In [38]:
percent=100*A/cal.reshape(1,4)#需要reshape成二维数组
print(percent)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


### 数组的广播

In [40]:
B=np.array([[56 , 0 ,4.4,68],
            [1.2,104, 52,8 ],
            [1.8,135, 99,0.9]])
C=np.array([[100],[200],[300]])
print(B+C)

[[156.  100.  104.4 168. ]
 [201.2 304.  252.  208. ]
 [301.8 435.  399.  300.9]]


### 不要用一维的数组而是二维

In [56]:
a= np.random.randn(5)
print(a)
print(a.T)
a= np.random.randn(1,5)
print(a)
print(a.T)

[-0.54314666  1.41273208 -2.12515794  0.19388156 -0.04860768]
[-0.54314666  1.41273208 -2.12515794  0.19388156 -0.04860768]
[[-1.25904052 -0.02380842  0.79981093 -0.01963671 -0.41885779]]
[[-1.25904052]
 [-0.02380842]
 [ 0.79981093]
 [-0.01963671]
 [-0.41885779]]


### numpy的x,y,z坐标的交换

In [5]:
import numpy as np
image=np.array([[1,2],[3,4]])
print(image)
image = image.transpose((1, 0))
print(image)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


交换行和列 法一

In [4]:
image=np.array([[1,2],[3,4]])
print(image)
print(image[[1,0]])
image2=image[[1,0],:]
print(image2)

[[1 2]
 [3 4]]
[[3 4]
 [1 2]]
[[3 4]
 [1 2]]


交换行和列 法二

In [12]:
image=np.array([[1,2],[3,4]])
print(image[[1,0]])


[[3 4]
 [1 2]]


### 拼接

concatenate

在哪个维度拼接哪个维度数量就增多

In [21]:
ar1=np.array([[1,2],[3,4]])
ar2=np.array([[5,6],[7,8]])

np.concatenate((ar1, ar2),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [20]:
np.concatenate((ar1, ar2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

append   会展开成1维度

In [19]:
np.append(ar1, ar2)

array([1, 2, 3, 4, 5, 6, 7, 8])

stack 会增加一个维度

In [22]:
np.stack((ar1, ar2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [32]:
np.stack((ar1, ar2),axis=1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [33]:
np.hstack((ar1,ar2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

vstack结果和concatenate的axis=0结果一样
vstack是列变长，axis-0是行变多

In [34]:
np.vstack((ar1,ar2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [35]:
ar1=np.array([[1,2,1,1],[3,4,1,1]])
ar2=np.array([[5,6,1,1],[7,8,1,1]])
np.vstack((ar1,ar2))

array([[1, 2, 1, 1],
       [3, 4, 1, 1],
       [5, 6, 1, 1],
       [7, 8, 1, 1]])