### 注意读进来的图片，pytorch自动加载的图片第一个通道是颜色

In [38]:
from PIL import Image
import numpy as np
img = Image.open(r"D:\deeplearning\pytorch_同济\028_034：图像识别核心模块实战解读\卷积网络实战\1.png")
img = np.array(img)
print(img.shape)


(354, 1667, 4)


In [37]:
img = Image.open(r"D:\deeplearning\pytorch_indoor\data\faces\10comm-decarlo.jpg")
img = np.array(img)
print(img.shape)

(250, 258, 3)


### shape 和 size（）

In [1]:
import os 
import torch
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

x = torch.randn(3,2,5,4,device=device)
#print(x)

conv = torch.nn.Conv2d(2,4,(2,3),device=device)
res = conv(x)

print(res.shape)    # torch.Size([3, 4, 4, 2])
print(res.size()) 

torch.Size([3, 4, 4, 2])
torch.Size([3, 4, 4, 2])


矩阵变换

In [3]:
import torch
data=[[1,2],[3,4]]
tensor=torch.FloatTensor(data)
print(tensor.reshape(4,1))
print(tensor.reshape(4,1).size())
print(tensor.view(-1,2))    # tensor.view()方法可以调整tensor的形状，但必须保证调整前后元素总数一致。
                            # view不会修改自身的数据，返回的新tensor与原tensor共享内存，即更改一个，另一个也随之改变
print(tensor)

tensor([[1.],
        [2.],
        [3.],
        [4.]])
torch.Size([4, 1])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])


### 解除梯度和复制

In [4]:
x = torch.randn(3,2,device=device)
print(x)
x = x.to("cpu").clone().detach()
print(x)

tensor([[-1.2603,  0.9908],
        [-0.3400, -1.3018],
        [ 0.9738,  0.5514]], device='cuda:0')
tensor([[-1.2603,  0.9908],
        [-0.3400, -1.3018],
        [ 0.9738,  0.5514]])


In [1]:
import torch
import numpy as np

np_data=np.arange(6).reshape((2,3))
torch_data=torch.tensor([1,2,3],dtype=torch.int32)

print(np_data)
print(torch_data)

[[0 1 2]
 [3 4 5]]
tensor([1, 2, 3], dtype=torch.int32)


### 增加维度

In [4]:
tensor.unsqueeze(0)

tensor([[[1., 2.],
         [3., 4.]]])

### 反向梯度 requires_grad=True

In [7]:
from torch.autograd import Variable

tensor=torch.FloatTensor([[1,2],[3,4]])
variable=Variable(tensor,requires_grad=True)


反向梯度

In [8]:
t_out=torch.mean(tensor*tensor)
v_out=torch.mean(variable*variable)
v_out.backward()
#v_out = 1/4*sum(tensor*tensor)
#dv_out/dvar=1/4*2*var
print(variable.grad)
print(variable)
print(variable.data)
print(variable.data.numpy())


tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[1., 2.],
        [3., 4.]])
[[1. 2.]
 [3. 4.]]


### clamp设置最小值

In [11]:
x = torch.randn(4,4)
print(x)
x = x.clamp(min=0)
print(x)

tensor([[-0.1227,  0.5728,  0.1618, -1.2737],
        [-0.8173, -1.9170,  0.4796, -1.6053],
        [ 0.0755, -0.3913,  0.9548, -1.4388],
        [ 1.3309, -0.4254,  0.5569, -1.3829]])
tensor([[0.0000, 0.5728, 0.1618, 0.0000],
        [0.0000, 0.0000, 0.4796, 0.0000],
        [0.0755, 0.0000, 0.9548, 0.0000],
        [1.3309, 0.0000, 0.5569, 0.0000]])


### 求最大值

In [29]:
x = torch.randn(4,4)
print(x)
data, index = torch.max(x, 0)
print( data, index)

tensor([[-0.3426,  1.0249,  1.4993,  0.9667],
        [-0.1284, -1.7554,  1.1140, -1.4146],
        [ 0.6946, -1.3141, -1.3764,  0.6439],
        [ 0.0720, -1.1401,  1.1311, -0.8952]])
tensor([0.6946, 1.0249, 1.4993, 0.9667]) tensor([2, 0, 0, 0])


### numpy用dot，tensor用mm,但 所以说mm不是简单的点乘，而是自定义的计算和反向梯度

In [12]:
import torch
device = torch.device("cuda:0")
N, D_in, H, D_out = 3, 4, 5, 2
w1 = torch.randn(D_in, H, device=device, dtype=torch.float)
x = torch.randn(N, D_in, device=device, dtype=torch.float)
h = x.mm(w1)
print(w1)
print(x)
print(h)
print(h.clamp(min=0))

tensor([[-0.7890,  1.1075, -0.0646,  0.1637, -0.2212],
        [ 0.5036, -0.9684, -1.3050,  0.6992,  1.4138],
        [-0.8618, -0.3875, -0.7452, -0.2451,  0.3027],
        [-1.3232,  1.4057,  2.3509, -1.6956, -0.9897]], device='cuda:0')
tensor([[-0.5545,  0.1147, -0.9228, -1.4858],
        [ 0.3888,  0.5982,  1.9038,  0.4557],
        [-1.0380,  0.2225,  0.4537,  0.7426]], device='cuda:0')
tensor([[ 3.2565, -2.4562, -2.9191,  2.7349,  1.4760],
        [-2.2493, -0.2457, -1.1531, -0.7575,  0.8849],
        [-0.4426, -0.4971,  1.1843, -1.3847, -0.0535]], device='cuda:0')
tensor([[3.2565, 0.0000, 0.0000, 2.7349, 1.4760],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.8849],
        [0.0000, 0.0000, 1.1843, 0.0000, 0.0000]], device='cuda:0')
