### numpy和torch之间的转换和函数

In [4]:
import torch
import numpy as np

In [5]:
torch_data=torch.tensor([1,2,3],dtype=torch.int32)

np_data=torch_data.numpy()
torch_rdata=torch.from_numpy(np_data)


print(np_data)
print(torch_rdata)

[1 2 3]
tensor([1, 2, 3], dtype=torch.int32)


### 列表变成tensor和numpy

In [6]:
data=[[1,2],[3,4]]
tensor=torch.FloatTensor(data)
data=np.array(data)
print(data)
print(tensor)

[[1 2]
 [3 4]]
tensor([[1., 2.],
        [3., 4.]])
